name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: |
          # Si tienes pruebas con pytest, puedes ejecutarlas aquí
          pytest

      # Paso 5: Crear la imagen Docker (si usas Docker)
      - name: Build Docker image
        run: |
          docker build -t flask_tienda .

      # Paso 6: Desplegar la aplicación (opcional)
      # Aquí puedes configurar un paso para desplegar la app a un servidor o a algún servicio como AWS, Heroku, etc.
      # Ejemplo para desplegar a Heroku (requiere tener configurado Heroku CLI):
      # - name: Deploy to Heroku
      #   run: |
      #     heroku login -i
      #     git remote add heroku https://git.heroku.com/<your-app>.git
      #     git push heroku main
