name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_tienda/requirements.txt

      # Paso 4: Listar paquetes instalados (opcional para depuración)
      - name: List installed packages
        run: pip list

      # Paso 5: Establecer PYTHONPATH y ejecutar las pruebas
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/flask_tienda
          pytest  # Ejecutar pytest después de que se haya instalado pytest
